:-op(0,fx,(dynamic)).
:-op(0,fx,(mode)).
:-op(0,fx,(module)).
:-op(0,fx,(public)).
:-op(0,fx,(memo)).
:-op(0,fx,(type)).
:-op(0,fx,(delphi)).
:-op(0,fx,(mod)).
:-op(0,xfx,(extends)).
:-op(0,xfx,(with)).
:-op(0,fy,(not)).
:-op(0,xfx,(is)).
:-op(0,fx,(discontiguous)).
:-op(0,fx,(multifile)).
:-op(0,fx,(spy)).
:-op(0,fx,(memo)).
:-op(0,fy,(~)).
